//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMC_Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMC_DBEntities : DbContext
    {
        public SMC_DBEntities()
            : base("name=SMC_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Balance> Balances { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemBalance> ItemBalances { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Subgroup> Subgroups { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual ObjectResult<GetTopTenSuppliers_Result> GetTopTenSuppliers(Nullable<int> itemID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("itemID", itemID) :
                new ObjectParameter("itemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopTenSuppliers_Result>("GetTopTenSuppliers", itemIDParameter);
        }
    
        public virtual ObjectResult<spGetLeastTenItems_Result> spGetLeastTenItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLeastTenItems_Result>("spGetLeastTenItems");
        }
    
        public virtual ObjectResult<spGetTopTenItems_Result> spGetTopTenItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTopTenItems_Result>("spGetTopTenItems");
        }
    }
}
