
export const environment = {
  
  Register: 'http://localhost:59156/api/account/register',
  Update: 'http://localhost:59156/api/account/Update',
  Delete: 'http://localhost:59156/api/account/Delete',
  User: 'http://localhost:59156/api/account/',
  Roles: 'http://localhost:59156/api/GetRoles/',
  Users: 'http://localhost:59156/api/account/Users/',
  Login: 'http://localhost:59156/token',
  Store: 'http://localhost:59156/api/Store/',
  DeleteStore: 'http://localhost:59156/api/DeleteStore/',
  Supplier: 'http://localhost:59156/api/Supplier/',
  Employee: 'http://localhost:59156/api/Employee/',
  DeleteSupplier: 'http://localhost:59156/api/DeleteSupplier/',
  Customer: 'http://localhost:59156/api/Customer/',
  DeleteCustomer: 'http://localhost:59156/api/DeleteCustomer/',
  Group: 'http://localhost:59156/api/Group/',
  DeleteGroup: 'http://localhost:59156/api/DeleteGroup/',
  Subgroup: 'http://localhost:59156/api/Subgroup/',
  SubgroupByGrpId: 'http://localhost:59156/api/SubgroupsByGrpId/',
  DeleteSubgroup: 'http://localhost:59156/api/DeleteSubgroup/',
  Item: 'http://localhost:59156/api/Item/',
  DeleteItem: 'http://localhost:59156/api/DeleteItem/',
  OrderType: 'http://localhost:59156/api/OrderType/',
  ActiveTypes: 'http://localhost:59156/api/GetActiveTypes/',
  DeleteType: 'http://localhost:59156/api/DeleteType/',
  Order: 'http://localhost:59156/api/Order/',
  OrderByStore: 'http://localhost:59156/api/OrderByStore/',
  DeleteOrder: 'http://localhost:59156/api/DeleteOrder/',
  Balance: 'http://localhost:59156/api/Balance/',
  BalanceByStore: 'http://localhost:59156/api/BalanceByStore/',
  DeleteBalance: 'http://localhost:59156/api/DeleteBalance/',
  LastBalance: 'http://localhost:59156/api/GetLastBalance/',
  GenericLastBalance: 'http://localhost:59156/api/GetGenericLastBalance/',
  AddBalance: 'http://localhost:59156/api/AddBalance/',
  TransactionReport: 'http://localhost:59156/api/GetOrdersByType',
  ExpiredItems: 'http://localhost:59156/api/ExpiredItemsWithinDays/',
  YearBalance: 'http://localhost:59156/api/YearBalance/',
  YearBalancePerQuarter: 'http://localhost:59156/api/YearBalancePerQuarter/',
  QuarterBalance: 'http://localhost:59156/api/QuarterBalance/',
  QuarterBalancePerMonth: 'http://localhost:59156/api/QuarterBalancePerMonth/',
  LastInOrder: 'http://localhost:59156/api/GetLastInOrder/',
  LastOutOrder: 'http://localhost:59156/api/GetLastOutOrder/',
  ItemsWhichNeedToReordered: 'http://localhost:59156/api/GetItemsWhichNeedToReordered/',
  production: false
};

